name: Feature request
description: Propose a new capability for WorkerFlow.
title: "[Feature] "
labels:
  - enhancement
body:
  - type: dropdown
    id: category
    attributes:
      label: Category
      options:
        - runtime
        - dashboard
        - connectors
        - developer-experience
        - docs
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What user outcome is currently blocked?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe the preferred implementation.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      placeholder: |
        - [ ] ...
        - [ ] ...
